In [1]:
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import time

In [22]:
# Years analyzing for MVP race
years = list(range(2000, 2024))

In [14]:
# Template url to pull request for awards
url_awards = "https://www.basketball-reference.com/awards/awards_{}.html"

In [15]:
# writes a file in mvp folder for each year in our range with an html file
# WE HAVE THIS RANGE OF DATA ALREADY
import requests

for year in years:
    url = url_awards.format(year)
    data = requests.get(url)
    
    with open("mvp/{}.html".format(year), "w+") as f:
        f.write(data.text)

In [17]:
# opening file for 2023
with open("mvp/2023.html") as f:
    page = f.read()

In [18]:
# creating html parser for that specific page
soup = BeautifulSoup(page, "html.parser")

In [20]:
# finding the mvp table
mvp_2023_table = soup.find(id="mvp")

In [21]:
# converting it into a pandas df
mvp_2023_pd = pd.read_html(str(mvp_2023_table))[0]
mvp_2023_pd

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Joel Embiid,28,PHI,73.0,915.0,1000,0.915,66,34.6,33.1,10.2,4.2,1.0,1.7,0.548,0.330,0.857,12.3,0.259
1,2,Nikola Jokić,27,DEN,15.0,674.0,1000,0.674,69,33.7,24.5,11.8,9.8,1.3,0.7,0.632,0.383,0.822,14.9,0.308
2,3,Giannis Antetokounmpo,28,MIL,12.0,606.0,1000,0.606,63,32.1,31.1,11.8,5.7,0.8,0.8,0.553,0.275,0.645,8.6,0.204
3,4,Jayson Tatum,24,BOS,0.0,280.0,1000,0.280,74,36.9,30.1,8.8,4.6,1.1,0.7,0.466,0.350,0.854,10.5,0.185
4,5,Shai Gilgeous-Alexander,24,OKC,0.0,46.0,1000,0.046,68,35.5,31.4,4.8,5.5,1.6,1.0,0.510,0.345,0.905,11.4,0.226
5,6,Donovan Mitchell,26,CLE,0.0,30.0,1000,0.030,68,35.8,28.3,4.3,4.4,1.5,0.4,0.484,0.386,0.867,8.9,0.176
6,7,Domantas Sabonis,26,SAC,0.0,27.0,1000,0.027,79,34.6,19.1,12.3,7.3,0.8,0.5,0.615,0.373,0.742,12.6,0.221
7,8,Luka Dončić,23,DAL,0.0,10.0,1000,0.010,66,36.2,32.4,8.6,8.0,1.4,0.5,0.496,0.342,0.742,10.2,0.204
8,9,Stephen Curry,34,GSW,0.0,5.0,1000,0.005,56,34.7,29.4,6.1,6.3,0.9,0.4,0.493,0.427,0.915,7.8,0.192
9,10,Jimmy Butler,33,MIA,0.0,3.0,1000,0.003,64,33.4,22.9,5.9,5.3,1.8,0.3,0.539,0.350,0.850,12.3,0.277
10,11,De'Aaron Fox,25,SAC,0.0,2.0,1000,0.002,73,33.4,25.0,4.2,6.1,1.1,0.3,0.512,0.324,0.780,7.4,0.146
11,12T,Jalen Brunson,26,NYK,0.0,1.0,1000,0.001,68,35.0,24.0,3.5,6.2,0.9,0.2,0.491,0.416,0.829,8.7,0.175
12,12T,Ja Morant,23,MEM,0.0,1.0,1000,0.001,61,31.9,26.2,5.9,8.1,1.1,0.3,0.466,0.307,0.748,6.0,0.148

In [25]:
# putting it in for loop for all years
dfs = []

for year in years:
    with open("mvp/{}.html".format(year)) as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find("tr", class_="over_header").decompose()
    mvp_table = soup.find(id="mvp")
    mvp = pd.read_html(str(mvp_table))[0]
    mvp["Year"] = year
    
    dfs.append(mvp)

AttributeError: 'NoneType' object has no attribute 'decompose'

In [26]:
dfs

[]

In [34]:
# concatenated df with mvp data for 2000-2023
mvps = pd.concat(dfs)
mvps

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Shaquille O'Neal,27,LAL,120.0,1207.0,1210,0.998,79,40.0,...,13.6,3.8,0.5,3.0,0.574,0.000,0.524,18.6,0.283,2000
1,2,Kevin Garnett,23,MIN,0.0,408.0,1210,0.337,81,40.0,...,11.8,5.0,1.5,1.6,0.497,0.370,0.765,11.6,0.172,2000
2,3,Alonzo Mourning,29,MIA,0.0,367.0,1210,0.303,79,34.8,...,9.5,1.6,0.5,3.7,0.551,0.000,0.711,12.9,0.226,2000
3,4,Karl Malone,36,UTA,0.0,312.0,1210,0.258,82,35.9,...,9.5,3.7,1.0,0.9,0.509,0.250,0.797,15.3,0.249,2000
4,5,Tim Duncan,23,SAS,0.0,248.0,1210,0.205,74,38.9,...,12.4,3.2,0.9,2.2,0.490,0.091,0.761,13.0,0.218,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,9,Stephen Curry,34,GSW,0.0,5.0,1000,0.005,56,34.7,...,6.1,6.3,0.9,0.4,0.493,0.427,0.915,7.8,0.192,2023
9,10,Jimmy Butler,33,MIA,0.0,3.0,1000,0.003,64,33.4,...,5.9,5.3,1.8,0.3,0.539,0.350,0.850,12.3,0.277,2023
10,11,De'Aaron Fox,25,SAC,0.0,2.0,1000,0.002,73,33.4,...,4.2,6.1,1.1,0.3,0.512,0.324,0.780,7.4,0.146,2023
11,12T,Jalen Brunson,26,NYK,0.0,1.0,1000,0.001,68,35.0,...,3.5,6.2,0.9,0.2,0.491,0.416,0.829,8.7,0.175,2023
12,12T,Ja Morant,23,MEM,0.0,1.0,1000,0.001,61,31.9,...,5.9,8.1,1.1,0.3,0.466,0.307,0.748,6.0,0.148,2023

In [35]:
mvps.to_csv("mvp_votes.csv")

## Now looking at Player Stats

In [36]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.10.0-py3-none-any.whl (6.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 10.6 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /Users/zayank/anaconda3/lib/python3.10/site-packages (from selenium) (1.26.14)
Requirement already satisfied: certifi>=2021.10.8 in /Users/zayank/anaconda3/lib/python3.10/site-packages (from selenium) (2022.12.7)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.10.3-py3-none-any.whl (17 kB)
Collecting trio~=0.17
  Downloading trio-0.22.0-py3-none-any.whl (384 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.9/384.9 kB 5.9 MB/s eta 0:00:00a 0:00:01
Collecting async-generator>=1.9
  Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Requirement already satisfied: sniffio in /Users/zayank/anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in /Users/zayank/anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=19.2.0 in /Users/zayank/anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (22.1.0)
Collecting outcome
  Downloading outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting exceptiongroup>=1.0.0rc9
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Requirement already satisfied: idna in /Users/zayank/anaconda3/lib/python3.10/site-packages (from trio~=0.17->selenium) (3.4)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Users/zayank/anaconda3/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 2.3 MB/s eta 0:00:00
Installing collected packages: outcome, h11, exceptiongroup, async-generator, wsproto, trio, trio-websocket, selenium
Successfully installed async-generator-1.10 exceptiongroup-1.1.1 h11-0.14.0 outcome-1.2.0 selenium-4.10.0 trio-0.22.0 trio-websocket-0.10.3 wsproto-1.2.0

In [47]:
# Creates driver from file path where it is it
service = Service(executable_path="/usr/local/bin")
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=service, options=options)

In [49]:
player_stats_pergame_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

In [50]:
# for loop to get html with all rows (including the parsed javascript) to get information
# driver.get(url) and execute_scripts gets the entire document
for year in years:
    url = player_stats_pergame_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1, 100000)")
    time.sleep(2)
    html = driver.page_source
    with open("perGame/{}.html".format(year), "w+") as f:
        f.write(html)

In [88]:
# beautiful soup finds table with that ID and then removes the thead
# comes in between the table so we can get a proper pandas dataframe

per_game_dfs = []

for year in years:
    with open("perGame/{}.html".format(year)) as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find("tr", class_="thead").decompose()
    per_game_table = soup.find(id="per_game_stats")
    per_game = pd.read_html(str(per_game_table))[0]
    per_game["Year"] = year
    per_game_dfs.append(per_game)

In [52]:
per_game_stats = pd.concat(per_game_dfs)

In [70]:
# removing header rows
per_game_stats = per_game_stats[(per_game_stats['Player'] != "Player") & (per_game_stats['Age'] != "Age")]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Tariq Abdul-Wahad,SG,25,TOT,61,56,25.9,4.5,10.6,...,1.7,3.1,4.8,1.6,1.0,0.5,1.7,2.4,11.4,2000
1,1,Tariq Abdul-Wahad,SG,25,ORL,46,46,26.2,4.8,11.2,...,1.7,3.5,5.2,1.6,1.2,0.3,1.9,2.5,12.2,2000
2,1,Tariq Abdul-Wahad,SG,25,DEN,15,10,24.9,3.4,8.7,...,1.6,1.9,3.5,1.7,0.4,0.8,1.3,2.1,8.9,2000
3,2,Shareef Abdur-Rahim,SF,23,VAN,82,82,39.3,7.2,15.6,...,2.7,7.4,10.1,3.3,1.1,1.1,3.0,3.0,20.3,2000
4,3,Cory Alexander,PG,26,DEN,29,2,11.3,1.0,3.4,...,0.3,1.2,1.4,2.0,0.8,0.1,1.0,1.3,2.8,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,49,Terrell Brandon,PG,29,MIN,71,71,36.4,6.8,14.7,...,0.6,2.7,3.4,8.9,1.9,0.4,2.6,2.2,17.1,2000
60,50,Chucky Brown,PF,31,TOT,63,29,17.4,2.3,5.2,...,0.6,2.1,2.7,1.0,0.3,0.3,0.7,1.8,5.3,2000
61,50,Chucky Brown,PF,31,SAS,30,27,20.1,2.7,5.9,...,0.4,2.2,2.6,1.4,0.3,0.3,0.9,1.8,6.3,2000
62,50,Chucky Brown,PF,31,CHH,33,2,15.0,2.0,4.6,...,0.7,2.0,2.7,0.8,0.4,0.2,0.5,1.8,4.4,2000
63,51,Dee Brown,PG,31,TOR,38,12,17.7,2.4,6.8,...,0.2,1.2,1.4,2.3,0.6,0.1,1.0,1.6,6.9,2000

In [71]:
per_game_stats.to_csv("per_game_stats.csv")

## Now using advanced stats (same code as pergame)

In [54]:
player_stats_advanced_url = "https://www.basketball-reference.com/leagues/NBA_{}_advanced.html"

In [55]:
# same code as pergame but instead for advanced
for year in years:
    url = player_stats_advanced_url.format(year)
    
    driver.get(url)
    driver.execute_script("window.scrollTo(1, 100000)")
    time.sleep(2)
    html = driver.page_source
    with open("advanced/{}.html".format(year), "w+") as f:
        f.write(html)

In [158]:
advanced_dfs = []

for year in years:
    with open("advanced/{}.html".format(year)) as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find("tr", class_="thead").decompose()
    advanced_table = soup.find(id="advanced_stats")
    advanced = pd.read_html(str(advanced_table))[0]
    advanced["Year"] = year
    advanced_dfs.append(advanced)

In [57]:
advanced_stats = pd.concat(advanced_dfs)

In [72]:
# removing header rows
advanced_stats = advanced_stats[(advanced_stats['Player'] != "Player") & (advanced_stats['Age'] != "Age")]

In [73]:
advanced_stats.to_csv("advanced_stats.csv")

## Team records per year

In [14]:
team_standings_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [15]:
# Get all team standings Data (used division standings since we can use requests.get() for af)

for year in years:
    url = team_standings_url.format(year)
    data = requests.get(url)
    
    with open("record/{}.html".format(year), "w+") as f:
        f.write(data.text)

In [16]:
# Lesson: only can run once because if you get nonetype it's because it's already been deleted

standings_dfs = []

for year in years:
    with open("record/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    
    # Eastern Conference
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    standings_dfs.append(e_df)
    
    # Western Conference
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    standings_dfs.append(w_df)

AttributeError: 'NoneType' object has no attribute 'decompose'

In [176]:
team_standings = pd.concat(standings_dfs)

In [177]:
team_standings = team_standings.loc[team_standings.W.str.isnumeric()]

In [178]:
team_standings.to_csv("records_csv")